apiVersion: v1
name: dck-istio-init
version: 1.1.7
appVersion: 1.1.7
tillerVersion: ">=2.7.2-0"
description: Helm chart to initialize Istio CRDs
keywords:
  - istio
  - crd
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
